### ISSUE TITLE
css location

### ISSUE THREAD

**Issue by torvista** [lat9/super_globals_plus#17]
No doubt you have thought long about this thorny issue (!), but anyway I'll stick in my 0.09 euros.
As things currently stand on the catalog side, 
if the output is in a popup, the css gets loaded from the current template css folder,
if the output is in the page footer, the css gets loaded from the current template css folder always: **whether superglobals is enabled or not**.

I tend to use Superglobals when I'm not understanding something, and may well switch between custom and core templates for comparison.
So when I first added this to my site, I put it in /templates/shared and edited the code accordingly.
This is ok for the popup use, which calls the link directly in it's head.
For the admin, I add an import in the main css since I don't care about that being efficient or not-touching a core file.
For the catalog, either 
- a hard-coded **if** has to go in the head section: not really an issue if it has already been modified for a template. But for comparison across templates it has to be in them all, which is not ideal/not very elegant

- I have a js function in use on my site which puts a css link in the head on demand. I use that when I have jscript embedded in a product description and want css with it.
At the moment I use that to put the SG css in the head on demand.

- Or some js in the superglobals_buffer code, could appendChild the css link to the head.
This would probably be best, but I could not get it to work with all the single and double quotation marks mixed in there with php. Maybe jquery would do it better.
I think this would be best way to make it work on all templates without modification of any of them....

**Comment by lat9** [comment]
Agreed, it's bothered me as well that the superglobals css file is always loaded.  I'll ponder your suggestions and post back.

**Comment by lat9** [comment]
How about doing a naughty (but it's debug code anyway) inclusion of the stylesheet just prior to the superglobals' output,  if the output is going to be rendered?

**Comment by torvista** [comment]
Since the only person on the planet who would complain about that html validator error would be me, I could live with that temporary agony, just for the permanent vanquishing of another stray add-on file from the vanilla fileset!
